name: Push Package

on:
  push:
    branches:
    - flutterflow
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shivangimaheshvari/s3-sync-action@master
        env:
          AWS_SECRET_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET }}
          BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}